too-many-lines-threshold       = 50
too-many-arguments-threshold   = 4
cognitive-complexity-threshold = 15
min-ident-chars-threshold      = 3
allowed-idents-below-min-chars = ["i", "j", "k", "x", "y", "z", "n", "T", "E", "ok", "id"]
single-char-binding-names-threshold = 0
max-struct-bools               = 2
max-fn-params-bools            = 1
type-complexity-threshold      = 200
missing-docs-in-crate-items    = true
check-private-items            = true
allow-unwrap-in-tests          = false
allow-expect-in-tests          = false
allow-panic-in-tests           = false
allow-dbg-in-tests             = false
allow-print-in-tests           = false
